### BASE URL

@baseUrl = http://localhost:8080/api

### ==============================

### AUTH

### ==============================

### Login (salva token automaticamente)

# @name login

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "victor64gaming@gmail.com",
  "password": "12345678"
}

###

### ==============================

### PERMISSIONS (PROTEGIDO)

### ==============================

### Criar permission

POST {{baseUrl}}/permissions
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "name": "USER_READ"
}

###

### Listar permissions

GET {{baseUrl}}/permissions
Authorization: Bearer {{login.response.body.token}}

###

### ==============================

### ROLES (PROTEGIDO)

### ==============================

### Criar role

POST {{baseUrl}}/roles
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "name": "ADMIN",
  "permissionIds": [1, 2]
}

###

### Listar roles

GET {{baseUrl}}/roles
Authorization: Bearer {{login.response.body.token}}

###

### Atualizar role

PUT {{baseUrl}}/roles/1
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "permissionIds": [1]
}

###

### Deletar role

DELETE {{baseUrl}}/roles/1
Authorization: Bearer {{login.response.body.token}}

###
